# -*- coding: utf-8 -*-
"""p7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1md6xQgnVp1noeQuJtE5vm8Cj4QWh4J0g
"""

print('hello')